In [28]:
import numpy as np


In [13]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
a.shape


(2, 5)

In [4]:
# Get Specific element[r,c]
a=[1,5]


In [6]:
print (a)

[1, 5]


In [10]:
# Get Specific element[r,c]
a=[1, 5]
print (a)

[1, 5]


In [16]:
# Get specific Row

a=[0,:]
print (a)

SyntaxError: invalid syntax (2590917323.py, line 3)

In [18]:
# Get Specific Column

a=[:,2]
print (a)

SyntaxError: invalid syntax (1166361600.py, line 3)

In [24]:
a=[0,1:-1:2]
print(a)

SyntaxError: invalid syntax (775059881.py, line 1)

In [48]:
a[1,5]=20
print=(a)

IndexError: index 5 is out of bounds for axis 1 with size 5

In [4]:
a=np.zeros((2,3))
array([[0.,0.,0.],[0.,0.,0.]])
print (a)

NameError: name 'np' is not defined

In [52]:
print (array)

NameError: name 'array' is not defined

AttributeError: module 'numpy' has no attribute 'zero'

In [6]:
np.zero((2,3))
array([[0.,0.,0.],[0.,0.,0.]])
print (array)


NameError: name 'np' is not defined

In [8]:
# All 0's matrix

np.zeros(2,3,3,2)


NameError: name 'np' is not defined

In [2]:
np.zeros(2,3)

NameError: name 'np' is not defined

In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

NameError: name 'np' is not defined

In [30]:
np.zeros((2,3))

NameError: name 'np' is not defined

In [12]:
a=np.array ([1,2,3])
b=a copy()
print(b)

SyntaxError: invalid syntax (872636039.py, line 2)